### ISSUE TITLE
Template image.html and settings

### ISSUE THREAD

**Issue by toccamonium-fe** [Hauer-Heinrich/hh_theme_default#3]
Hi Heinrich,

I'd like to use the Image.html partial template file for generating RWD images, is this a good idea as you writing "under heavy delevopment" :D 
And if I want to change image settings, where can I find configuration for? Thanks a lot!

**Comment by Teisi** [comment]
you could use whatever you want :)
For the Image Partial please note that your server should be able to handle webp file format (or delete the corresponding area in the Partial) - same thing with "cropVariant='smartphone'" if you haven't this cropVariant, then i would say change this to your needs or at least to "default"...

"under heavy development" means here:
- it is not a read to use theme/distribution
- it may have bugs
- it doesn't have an update path
- things will change from time to time without us taking care if this (change) is "breaking" - in the near future especially CSS theming

We use this more like a "skeleton" for new projects. To have always the same structure and as good as possible always the more or less same Config (TypoScript - UserTs - PageTs - AdditionalConfig etc.).

_And if I want to change image settings, where can I find configuration for? Thanks a lot!_
What do you mean? What would you like to change?

**Comment by toccamonium-fe** [comment]
Hi, thanks for feedback. Now everything is clear :)
